// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907164616_AddZoneToStation")]
    partial class AddZoneToStation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("api.Models.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RunningDays")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TrainNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainNumber")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("api.Models.TrainStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("ArrivalTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("DepartureTime")
                        .HasColumnType("time without time zone");

                    b.Property<decimal>("DistanceFromOrigin")
                        .HasColumnType("numeric");

                    b.Property<int>("StationId")
                        .HasColumnType("integer");

                    b.Property<int>("StopOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TrainId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("TrainId");

                    b.ToTable("TrainStops");
                });

            modelBuilder.Entity("api.Models.TrainZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Headquarters")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TrainZones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CR",
                            Headquarters = "Mumbai",
                            Name = "Central Railway"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ER",
                            Headquarters = "Kolkata",
                            Name = "Eastern Railway"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ECR",
                            Headquarters = "Hajipur",
                            Name = "East Central Railway"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ECoR",
                            Headquarters = "Bhubaneswar",
                            Name = "East Coast Railway"
                        },
                        new
                        {
                            Id = 5,
                            Code = "NR",
                            Headquarters = "New Delhi",
                            Name = "Northern Railway"
                        },
                        new
                        {
                            Id = 6,
                            Code = "NCR",
                            Headquarters = "Prayagraj",
                            Name = "North Central Railway"
                        },
                        new
                        {
                            Id = 7,
                            Code = "NER",
                            Headquarters = "Gorakhpur",
                            Name = "North Eastern Railway"
                        },
                        new
                        {
                            Id = 8,
                            Code = "NFR",
                            Headquarters = "Guwahati",
                            Name = "Northeast Frontier Railway"
                        },
                        new
                        {
                            Id = 9,
                            Code = "NWR",
                            Headquarters = "Jaipur",
                            Name = "North Western Railway"
                        },
                        new
                        {
                            Id = 10,
                            Code = "SR",
                            Headquarters = "Chennai",
                            Name = "Southern Railway"
                        },
                        new
                        {
                            Id = 11,
                            Code = "SCR",
                            Headquarters = "Secunderabad",
                            Name = "South Central Railway"
                        },
                        new
                        {
                            Id = 12,
                            Code = "SER",
                            Headquarters = "Kolkata",
                            Name = "South Eastern Railway"
                        },
                        new
                        {
                            Id = 13,
                            Code = "SECR",
                            Headquarters = "Bilaspur",
                            Name = "South East Central Railway"
                        },
                        new
                        {
                            Id = 14,
                            Code = "SWR",
                            Headquarters = "Hubballi",
                            Name = "South Western Railway"
                        },
                        new
                        {
                            Id = 15,
                            Code = "WR",
                            Headquarters = "Mumbai",
                            Name = "Western Railway"
                        },
                        new
                        {
                            Id = 16,
                            Code = "WCR",
                            Headquarters = "Jabalpur",
                            Name = "West Central Railway"
                        },
                        new
                        {
                            Id = 17,
                            Code = "KR",
                            Headquarters = "Navi Mumbai",
                            Name = "Konkan Railway"
                        },
                        new
                        {
                            Id = 18,
                            Code = "METRO",
                            Headquarters = "Kolkata",
                            Name = "Kolkata Metro Railway"
                        });
                });

            modelBuilder.Entity("api.Models.Station", b =>
                {
                    b.HasOne("api.Models.TrainZone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("api.Models.Train", b =>
                {
                    b.HasOne("api.Models.TrainZone", "Zone")
                        .WithMany("Trains")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("api.Models.TrainStop", b =>
                {
                    b.HasOne("api.Models.Station", "Station")
                        .WithMany("TrainStops")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("api.Models.Train", "Train")
                        .WithMany("TrainStops")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("api.Models.Station", b =>
                {
                    b.Navigation("TrainStops");
                });

            modelBuilder.Entity("api.Models.Train", b =>
                {
                    b.Navigation("TrainStops");
                });

            modelBuilder.Entity("api.Models.TrainZone", b =>
                {
                    b.Navigation("Trains");
                });
#pragma warning restore 612, 618
        }
    }
}
